# Generated by Django 5.0.6 on 2024-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='parents_mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
