# Generated by Django 5.0.6 on 2024-09-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsend', '0002_students_parents_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='parents_mail',
        ),
        migrations.AddField(
            model_name='students',
            name='is_inside',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parents_mail_1',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='parents_mail_2',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
